language: node_js
sudo: false
node_js:
  - "0.12"
install:
  - npm install -g grunt-cli
  - npm install -g mocha
  - npm install
before_script:
  - grunt --version
  - mocha --version
  - grunt
script:
  - mocha
